apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 703708126540.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 703708126540.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 7c0ae5ab
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
